### ISSUE TITLE
issue with python package installation

### ISSUE THREAD

**Issue by zohaibtechknox** [dozzie/yumbootstrap#24]
in chroot environment when i try to install python packages  I am getting this issue
`Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-UFsQuw/positional/setup.py", line 20, in <module>
        import multiprocessing  # noqa
      File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 64, in <module>
        from multiprocessing.process import Process, current_process, active_children
      File "/usr/lib64/python2.7/multiprocessing/process.py", line 312, in <module>
        _current_process = _MainProcess()
      File "/usr/lib64/python2.7/multiprocessing/process.py", line 309, in __init__
        self._authkey = AuthenticationString(os.urandom(32))
    NotImplementedError: /dev/urandom (or equivalent) not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-UFsQuw/positional/
`
I have try to update python setuptools but still having this issue

**Comment by dozzie** [comment]
I don't see how this is related to yumbootstrap. And you have what seems to be precise error message there in the last line of stack trace.
