### ISSUE TITLE
build failure with 'AttributeError: 'NoneType' object has no attribute 'ensure_finalized''

### ISSUE THREAD

**Issue by Whishay** [dozzie/yumbootstrap#32]
Copying lib/yumbootstrap.egg-info to /root/rpmbuild/BUILDROOT/yumbootstrap-0.0.3-1.el7.x86_64/usr/lib/python2.7/site-packages/yumbootstrap-0.0.3-py2.7.egg-info
running install_scripts
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    package_dir  = { "": "lib" },
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
    return orig.install.run(self)
  File "/usr/lib64/python2.7/distutils/command/install.py", line 575, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install_scripts.py", line 33, in run
    bs_cmd = (self.get_finalized_command('build_scripts', create=False) or
  File "/usr/lib64/python2.7/distutils/cmd.py", line 312, in get_finalized_command
    cmd_obj.ensure_finalized()
AttributeError: 'NoneType' object has no attribute 'ensure_finalized'
error: Bad exit status from /var/tmp/rpm-tmp.2G0Cvk (%install)

**Comment by Whishay** [comment]
After done it on Fedora 27 instead on centos, this issue could be resolved.
